#!/usr/bin/env bash
VIMDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Remove existing config files
rm ~/.{vimrc,gvimrc}

# Symlink
ln -s $VIMDIR/vimrc $HOME/.vimrc
ln -s $VIMDIR/gvimrc $HOME/.gvimrc

# Create directories
mkdir -p $VIMDIR/{tmp,view,backup,session}

# Download Vundle
git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# We must explicitly set the shell to Bash or Vim will fail under Fish
# https://github.com/gmarik/vundle/wiki
SHELL=bash

# Install bundles
vim +BundleInstall +qall

# Setup Tern
cd $VIMDIR/bundle/tern_for_vim && npm install
cd $VIMDIR

# Setup YouCompleteMe
$VIMDIR/bundle/YouCompleteMe/install.py --clang-completer --gocode-completer --tern-completer

unset VIMDIR

echo
echo 'Done.'
echo
