#!/usr/bin/env bash

VIMDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Remove existing config files
rm ~/.{vimrc,gvimrc}

# Symlink
ln -s $VIMDIR/vimrc $HOME/.vimrc
ln -s $VIMDIR/gvimrc $HOME/.gvimrc

# Create directories
mkdir -p $VIMDIR/{tmp,view,backup,session}

# Download Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# We must explicitly set the shell to Bash or Vim will fail under Fish
# https://github.com/gmarik/vundle/wiki
SHELL=bash

# Install bundles
vim +BundleInstall +qall

# Setup Tern
cd $VIMDIR/bundle/tern_for_vim && npm install
cd $VIMDIR

# Arch Linux requires an extra flag
extraflags=''
[[ $(cat /etc/issue) =~ 'Arch Linux' ]] && extraflags='--system-libclang'

# Build YouCompleteMe
$VIMDIR/build-ycm

# Build Vimproc
#cd $VIMDIR/bundle/vimproc && make

unset VIMDIR

echo
echo 'Done.'
echo
