syn match javaScriptDollarVariable "\$"
syn match javaScriptOperator "\v[?+!<>=-]{1}"
syn match javaScriptOperator "\v(\||\&){2}"
syn match javaScriptOperator "\v(\*|/|\%)"
syn match javaScriptPunctuation "\v[.,;]{1}"
syn match javaScriptStatement "yield"
